
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 23 01:27:48 BST 2014
//----------------------------------------------------

package egp.concurrent.symbols;

/** CUP generated class containing symbol constants. */
public class boolsym {
  /* terminals */
  public static final int SETELEMENT = 41;
  public static final int GREATERTHAN = 29;
  public static final int AGENT = 6;
  public static final int GREATERTHANEQUAL = 30;
  public static final int KNOWS = 7;
  public static final int INTEGER = 3;
  public static final int NOTEQUAL = 31;
  public static final int LPAREN = 15;
  public static final int SEMI = 14;
  public static final int INIT = 9;
  public static final int FIN = 10;
  public static final int MINUS = 24;
  public static final int LESSTHANEQUAL = 28;
  public static final int RPAREN = 16;
  public static final int NOT = 40;
  public static final int AND = 37;
  public static final int OR = 38;
  public static final int LESSTHAN = 27;
  public static final int COMMA = 18;
  public static final int IMPLIES = 39;
  public static final int COMPLEMENT = 36;
  public static final int EMPTYSET = 11;
  public static final int BEGIN = 12;
  public static final int PLUS = 23;
  public static final int MULTIPLY = 22;
  public static final int EOF = 0;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int PIPE = 21;
  public static final int INTERSECTION = 35;
  public static final int SECRET = 8;
  public static final int AGENT_IDENTIFIER = 2;
  public static final int PROPERSUBSET = 33;
  public static final int SUBSET = 32;
  public static final int COLON = 17;
  public static final int UNION = 34;
  public static final int LBRACE = 19;
  public static final int DOUBLEEQUAL = 26;
  public static final int RBRACE = 20;
  public static final int MODULUS = 25;
  public static final int END = 13;
  public static final int NOTSETELEMENT = 42;
  public static final int FALSE = 5;
}

