
/**
 *
 * @author Maduka Attamah
 *
 * Copyright 2011-2015 Maduka Attamah
 *
 */

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 24 02:41:09 BST 2014
//----------------------------------------------------

package egp.concurrent.symbols;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SETELEMENT = 45;
  public static final int GREATERTHAN = 33;
  public static final int GREATERTHANEQUAL = 34;
  public static final int KNOWS = 6;
  public static final int NEIGHBOUR = 48;
  public static final int ASSIGNMENT = 50;
  public static final int NOTEQUAL = 35;
  public static final int INTEGER = 3;
  public static final int LPAREN = 19;
  public static final int SEMI = 18;
  public static final int DISJUNCT = 10;
  public static final int INIT = 13;
  public static final int FIN = 14;
  public static final int MINUS = 28;
  public static final int LESSTHANEQUAL = 32;
  public static final int RPAREN = 20;
  public static final int NOT = 44;
  public static final int AND = 41;
  public static final int EQUIV_NOTION = 49;
  public static final int OR = 42;
  public static final int LESSTHAN = 31;
  public static final int TOPOLOGY = 47;
  public static final int COMMA = 22;
  public static final int CALL = 7;
  public static final int IMPLIES = 43;
  public static final int COMPLEMENT = 40;
  public static final int EMPTYSET = 15;
  public static final int BEGIN = 16;
  public static final int PLUS = 27;
  public static final int MULTIPLY = 26;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int PIPE = 25;
  public static final int INTERSECTION = 39;
  public static final int SECRET = 12;
  public static final int CONJUNCT = 11;
  public static final int AGENT_IDENTIFIER = 2;
  public static final int PROPERSUBSET = 37;
  public static final int SUBSET = 36;
  public static final int COLON = 21;
  public static final int UNION = 38;
  public static final int LBRACE = 23;
  public static final int LET = 8;
  public static final int DOUBLEEQUAL = 30;
  public static final int RBRACE = 24;
  public static final int MODULUS = 29;
  public static final int END = 17;
  public static final int NOTSETELEMENT = 46;
  public static final int FALSE = 5;
}

